### ISSUE TITLE
Optional parameter for allowing negative numbers added. 

### ISSUE THREAD

**Issue by AliCharper** [LeoTanoue/ngx-currency-mask#2]
Hi,

I have not been able to activate this feature. 

On Edit mode the the indicative of negative number is the minus "-" sign, but when formatted we surround the value with parenthesis. So on input -300.12 will display as ($300.12).

May I know how can I activate this feature ?.

**Comment by LeoTanoue** [comment]
Try adding the allowNegative="true" in your input tag using the directive. That should turn on to allow negative numbers

**Comment by AliCharper** [comment]
Thanks ,but I need parenthesis around negative values. This is my problem. Accepting negative values is okay.

Something like this (123) in case of having -123

**Comment by LeoTanoue** [comment]
I understand. For this directive, if you set the allowNegative="true" flag in a input tag, after the user enters -200 it will display it as ($200.00) on blur.

for example:
`<input appCurrencyMask allowNegative="true" placeholder="Amount" formControlName="Amount" />`

**Comment by AliCharper** [comment]
It does not work. Can you provide me a sample?.

**Comment by LeoTanoue** [comment]
Hmm what exactly isn't working? An example is posted just above. Make sure you are importing the CurrencyMaskModule in whatever module you are trying to use it in

**Comment by AliCharper** [comment]
Everything is working fine except having () around negative values.

**Comment by LeoTanoue** [comment]
That's weird, I can't think of a reason, it's working on my side. Can you send me some of your code or a test application with the issue so I can take a look?

**Comment by AliCharper** [comment]
The only difference is that we do set all the configs inside a general place to not to be forced to set the configs for each input.

**Comment by AliCharper** [comment]
Can you please provide us a sample in an Angular CLI project ?. I am going to cry.

**Comment by AliCharper** [comment]
It works fine when we have added the services. Thanks for your support.
